### ISSUE TITLE
Mac m1

### ISSUE THREAD

**Issue by highfreq** [jostasik/Flowgorithm-macOS#16]
Hello, is this supposed to work on m1 apple silicon?

thanks.

**Comment by jostasik** [comment]
Yes it should be! Try this new release [Here](https://github.com/jostasik/Flowgorithm-macOS/releases/download/v3.4.2/Flowgorithm_v3.4.2.zip)

However if you still have issues then you may clone the repo or download the repository [Here](https://github.com/jostasik/Flowgorithm-macOS/archive/refs/heads/main.zip),and then run the Flowgorithm.app that is inside of it. 

Please let me know after you try!

**Comment by IlSuperGallo** [comment]
Thank you, now on my mac with M1 works perfectly.
