### ISSUE TITLE
Conflict version number in the release build

### ISSUE THREAD

**Issue by nuntipat** [jostasik/Flowgorithm-macOS#4]
Thank you for sharing your amazing work. I've tested the build on Monterey, and it functions flawlessly. I have a question regarding the build's version of Flowalgorithm. The [releases page](https://github.com/gogorama/Flowegorithm-macOS/releases/tag/v2.30.3) mentions both version 2.30.3 and version 3.1.2. In addition, the version number was rolled back in a recent [commit](https://github.com/gogorama/Flowgorithm-macOS/commit/07c7e0313b7bc489dfd7ef9d4c172d4b774030ec). Does Flowgorithm 3 have any issues that prohibit it from running on macOS?

**Comment by gogorama** [comment]
Hi! Yes that is correct. 
I rolled it back after discovering a major bug in the v3.1.2 GUI which appeared to prevent any popup dialog boxes from populating. It is currently on the back-burner but I should be able to spend some time on it within the next few weeks 😊
