### ISSUE TITLE
(Homebrew) Downloading Error. Can't find package.

### ISSUE THREAD

**Issue by noprobono** [jostasik/Flowgorithm-macOS#6]
Homebrew install not working! I tapped your repo. And then after entering "brew install flowgorithm" it begins to download but then throws up an error saying "flowgorithm.app can not be found"

**Comment by jostasik** [comment]
Whoops, sorry! I see. There was a typo in my "homebrew-tap" repository. Working fine now :) 
![Untitled](https://user-images.githubusercontent.com/31175268/193842891-4a944783-df47-4689-8d14-e3cbd899bad6.png)
