### ISSUE TITLE
Cannot type symbols using option + key

### ISSUE THREAD

**Issue by rhxto** [jostasik/Flowgorithm-macOS#8]
**Describe the bug**
Whenever I try to type any symbol using option + key it doesn't work and I get an invalid key sound.

**To Reproduce**
1. Go to any dialog
2. type option + any key

**Expected behavior**
The symbol I want to type appears.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - MacOS Version: Monterey 12.6
 - Device Macbook Pro
 - Year 2022

**Additional context**
I'm using the Italian keyboard layout.
If I type the symbols on another program then copy and paste them everything works.

Thanks for this amazing program! I've been using it for a while and this is the only issue I've had since then.

**Comment by jostasik** [comment]
Hello!

So as for symbols, Ive actually only ever needed to use ***!@#$%^&*()***, from using the *Shift+Any Key* combination.

And until now, I didn't even know that pressing the **Option+Any Key** combination was used to make any extra symbols! 
Those symbols aren't labeled on the American keyboard, but I just Googled the Italian keyboard and I see exactly what you're talking about.

I will definitely look into this later today and let you know when I fix it!


And thank you very much for the kind words, I appreciate it! 😀

**Comment by jostasik** [comment]
Hello again @rhxto ! It should be all fixed now. 

Here's the update: https://github.com/jostasik/Flowgorithm-macOS/releases/download/testing-v3.3.1.1/Flowgorithm-macOS-v3.3.1.1.zip

Please let me know if this fixes the issue for you as well! 
I'll then publish this as an official update 😊

**Comment by rhxto** [comment]
Everything works now!
Thank you for all the support.
